require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DquestionsController do

  # This should return the minimal set of attributes required to create a valid
  # Dquestion. As you add validations to Dquestion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DquestionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dquestions as @dquestions" do
      dquestion = Dquestion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dquestions).should eq([dquestion])
    end
  end

  describe "GET show" do
    it "assigns the requested dquestion as @dquestion" do
      dquestion = Dquestion.create! valid_attributes
      get :show, {:id => dquestion.to_param}, valid_session
      assigns(:dquestion).should eq(dquestion)
    end
  end

  describe "GET new" do
    it "assigns a new dquestion as @dquestion" do
      get :new, {}, valid_session
      assigns(:dquestion).should be_a_new(Dquestion)
    end
  end

  describe "GET edit" do
    it "assigns the requested dquestion as @dquestion" do
      dquestion = Dquestion.create! valid_attributes
      get :edit, {:id => dquestion.to_param}, valid_session
      assigns(:dquestion).should eq(dquestion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dquestion" do
        expect {
          post :create, {:dquestion => valid_attributes}, valid_session
        }.to change(Dquestion, :count).by(1)
      end

      it "assigns a newly created dquestion as @dquestion" do
        post :create, {:dquestion => valid_attributes}, valid_session
        assigns(:dquestion).should be_a(Dquestion)
        assigns(:dquestion).should be_persisted
      end

      it "redirects to the created dquestion" do
        post :create, {:dquestion => valid_attributes}, valid_session
        response.should redirect_to(Dquestion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dquestion as @dquestion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dquestion.any_instance.stub(:save).and_return(false)
        post :create, {:dquestion => {}}, valid_session
        assigns(:dquestion).should be_a_new(Dquestion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dquestion.any_instance.stub(:save).and_return(false)
        post :create, {:dquestion => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dquestion" do
        dquestion = Dquestion.create! valid_attributes
        # Assuming there are no other dquestions in the database, this
        # specifies that the Dquestion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dquestion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dquestion.to_param, :dquestion => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dquestion as @dquestion" do
        dquestion = Dquestion.create! valid_attributes
        put :update, {:id => dquestion.to_param, :dquestion => valid_attributes}, valid_session
        assigns(:dquestion).should eq(dquestion)
      end

      it "redirects to the dquestion" do
        dquestion = Dquestion.create! valid_attributes
        put :update, {:id => dquestion.to_param, :dquestion => valid_attributes}, valid_session
        response.should redirect_to(dquestion)
      end
    end

    describe "with invalid params" do
      it "assigns the dquestion as @dquestion" do
        dquestion = Dquestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dquestion.any_instance.stub(:save).and_return(false)
        put :update, {:id => dquestion.to_param, :dquestion => {}}, valid_session
        assigns(:dquestion).should eq(dquestion)
      end

      it "re-renders the 'edit' template" do
        dquestion = Dquestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dquestion.any_instance.stub(:save).and_return(false)
        put :update, {:id => dquestion.to_param, :dquestion => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dquestion" do
      dquestion = Dquestion.create! valid_attributes
      expect {
        delete :destroy, {:id => dquestion.to_param}, valid_session
      }.to change(Dquestion, :count).by(-1)
    end

    it "redirects to the dquestions list" do
      dquestion = Dquestion.create! valid_attributes
      delete :destroy, {:id => dquestion.to_param}, valid_session
      response.should redirect_to(dquestions_url)
    end
  end

end
