require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DteorsController do

  # This should return the minimal set of attributes required to create a valid
  # Dteor. As you add validations to Dteor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DteorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dteors as @dteors" do
      dteor = Dteor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dteors).should eq([dteor])
    end
  end

  describe "GET show" do
    it "assigns the requested dteor as @dteor" do
      dteor = Dteor.create! valid_attributes
      get :show, {:id => dteor.to_param}, valid_session
      assigns(:dteor).should eq(dteor)
    end
  end

  describe "GET new" do
    it "assigns a new dteor as @dteor" do
      get :new, {}, valid_session
      assigns(:dteor).should be_a_new(Dteor)
    end
  end

  describe "GET edit" do
    it "assigns the requested dteor as @dteor" do
      dteor = Dteor.create! valid_attributes
      get :edit, {:id => dteor.to_param}, valid_session
      assigns(:dteor).should eq(dteor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dteor" do
        expect {
          post :create, {:dteor => valid_attributes}, valid_session
        }.to change(Dteor, :count).by(1)
      end

      it "assigns a newly created dteor as @dteor" do
        post :create, {:dteor => valid_attributes}, valid_session
        assigns(:dteor).should be_a(Dteor)
        assigns(:dteor).should be_persisted
      end

      it "redirects to the created dteor" do
        post :create, {:dteor => valid_attributes}, valid_session
        response.should redirect_to(Dteor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dteor as @dteor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dteor.any_instance.stub(:save).and_return(false)
        post :create, {:dteor => {}}, valid_session
        assigns(:dteor).should be_a_new(Dteor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dteor.any_instance.stub(:save).and_return(false)
        post :create, {:dteor => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dteor" do
        dteor = Dteor.create! valid_attributes
        # Assuming there are no other dteors in the database, this
        # specifies that the Dteor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dteor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dteor.to_param, :dteor => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dteor as @dteor" do
        dteor = Dteor.create! valid_attributes
        put :update, {:id => dteor.to_param, :dteor => valid_attributes}, valid_session
        assigns(:dteor).should eq(dteor)
      end

      it "redirects to the dteor" do
        dteor = Dteor.create! valid_attributes
        put :update, {:id => dteor.to_param, :dteor => valid_attributes}, valid_session
        response.should redirect_to(dteor)
      end
    end

    describe "with invalid params" do
      it "assigns the dteor as @dteor" do
        dteor = Dteor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dteor.any_instance.stub(:save).and_return(false)
        put :update, {:id => dteor.to_param, :dteor => {}}, valid_session
        assigns(:dteor).should eq(dteor)
      end

      it "re-renders the 'edit' template" do
        dteor = Dteor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dteor.any_instance.stub(:save).and_return(false)
        put :update, {:id => dteor.to_param, :dteor => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dteor" do
      dteor = Dteor.create! valid_attributes
      expect {
        delete :destroy, {:id => dteor.to_param}, valid_session
      }.to change(Dteor, :count).by(-1)
    end

    it "redirects to the dteors list" do
      dteor = Dteor.create! valid_attributes
      delete :destroy, {:id => dteor.to_param}, valid_session
      response.should redirect_to(dteors_url)
    end
  end

end
